name: dla_bz
description: A new Flutter project.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  easy_localization: ^3.0.2
  auto_route: ^7.8.3
  image_picker: ^1.0.2
  url_launcher: ^6.1.14

  #UI
  flutter_svg: ^2.0.7
  cached_network_image: ^3.2.3
  intl_phone_field: ^3.2.0
  shimmer: ^3.0.0
  lottie: ^2.6.0
  flutter_styled_toast: ^2.1.3
  syncfusion_flutter_charts: ^23.1.38
  syncfusion_flutter_datepicker: ^23.1.36
  percent_indicator: ^4.2.3

  #  calendar_date_picker2: ^0.5.3
  intl_phone_number_input: ^0.7.3+1

  # STATE MANAGEMENT
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  provider: ^6.0.5
  get_it: ^7.6.0

  #NERWORK
  dio: ^5.3.2
  pretty_dio_logger: ^1.3.1
  retrofit: ^4.0.1
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  firebase_core: ^2.15.1

  #DB
  shared_preferences: ^2.2.0



  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  auto_route_generator: ^7.3.1
  build_runner: ^2.4.6
  retrofit_generator: ^7.0.8
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/png/favicon.png"
  min_sdk_android: 21

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/png/
    - assets/svg/
    - assets/translations/
    - assets/lottie/

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Gilroy-Bold.ttf
          weight: 700
        - asset: assets/fonts/Gilroy-Medium.ttf
          weight: 500
        - asset: assets/fonts/Gilroy-Medium.ttf
          weight: 600
        - asset: assets/fonts/Gilroy-Regular.ttf
          weight: 400